// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqEP3AT-g_PHsDbLjfYeNca64JAUNbm3Y',
    appId: '1:311090793664:web:482cc2a31bebc6f3863125',
    messagingSenderId: '311090793664',
    projectId: 'nwm-test-370017',
    authDomain: 'nwm-test-370017.firebaseapp.com',
    storageBucket: 'nwm-test-370017.appspot.com',
    measurementId: 'G-5536J5FJ0E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHTs_jMyhfKPP1ntOwI_MEHXLeTT9bHk8',
    appId: '1:311090793664:android:ed1a151a64d5cfc1863125',
    messagingSenderId: '311090793664',
    projectId: 'nwm-test-370017',
    storageBucket: 'nwm-test-370017.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbx87KoIU0DVi_Q1suATVefjrGqZFWhKY',
    appId: '1:311090793664:ios:742d2c108d83a783863125',
    messagingSenderId: '311090793664',
    projectId: 'nwm-test-370017',
    storageBucket: 'nwm-test-370017.appspot.com',
    iosClientId: '311090793664-gakfku016ft4r0rb1ev7cq4pjuaoeoed.apps.googleusercontent.com',
    iosBundleId: 'com.example.nwmRiverForecast',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbx87KoIU0DVi_Q1suATVefjrGqZFWhKY',
    appId: '1:311090793664:ios:742d2c108d83a783863125',
    messagingSenderId: '311090793664',
    projectId: 'nwm-test-370017',
    storageBucket: 'nwm-test-370017.appspot.com',
    iosClientId: '311090793664-gakfku016ft4r0rb1ev7cq4pjuaoeoed.apps.googleusercontent.com',
    iosBundleId: 'com.example.nwmRiverForecast',
  );
}
